Apply suggestions from code review
CypressError: Cypress.env() does not work when allowCypressEnv is set to false. Please migrate to cy.env() or leverage other stateful methods to manage variables. The variable being accessed was: sitename

Co-authored-by: Stefan Wendhausen <stefan.wendhausen@tec-promotion.de>